//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public class EZFunSwitchBtnSprite : MonoBehaviour {
	// Use this for initialization
	public string m_firstSprite;
	public string m_nextSprite;
	private bool m_showFlag = true;

	void Start () {
		
	}
	
	void OnClick () {
		m_showFlag = !m_showFlag;
		if (m_showFlag) {
			this.GetComponentInChildren<UISprite> ().spriteName = m_firstSprite;
//			this.GetComponentInChildren<UIButton> ().normalSprite = m_firstSprite;
		}
		else{
			this.GetComponentInChildren<UISprite>().spriteName = m_nextSprite;
//			this.GetComponentInChildren<UIButton>().normalSprite = m_nextSprite;
         }
    }

	void Update()
	{
	}
}