//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEditor;
using UnityEngine;

[InitializeOnLoad]
public class RunEditor  {

	static RunEditor() {
		EditorApplication.playmodeStateChanged += ()=> {
			if (EditorApplication.isPlaying == false 
			    && EditorApplication.isPaused == false 
			    && EditorApplication.isPlayingOrWillChangePlaymode == false) {
				try
				{
					System.IO.StreamReader f = new System.IO.StreamReader(UnityEngine.Application.dataPath + "runEditor");
					string s = f.ReadToEnd();
					f.Close();
					var wf = new System.IO.StreamWriter(UnityEngine.Application.dataPath + "runEditor");
					wf.Write("");
					Debug.Log("open pre scene" + s);
					if (!s.Equals("")) {
						EditorApplication.OpenScene(s);
					}
				}
				catch
				{

				}
			}
		};
	}
	
	[MenuItem ("EZFun/run/play &%#r")]
	static void Run ()
	{	
		System.IO.StreamWriter f = new System.IO.StreamWriter(UnityEngine.Application.dataPath + "runEditor");
		f.Write(EditorApplication.currentScene);
		f.Close();
		EditorApplication.OpenScene("Assets/XGame/Scene/Release/GameRoot.unity");
		EditorApplication.isPlaying = true;
	}
	
	[MenuItem ("EZFun/run/stop &%#s")]
	static void Stop()
	{	
		EditorApplication.isPlaying = false;
	}
	
}
