using System;

public static class LuaBinder
{
	public static void Bind(IntPtr L)
	{
		objectWrap.Register(L);
		ObjectWrap.Register(L);
		BehaviourWrap.Register(L);
		AdaptTypeWrap.Register(L);
		BaseUIWrap.Register(L);
		BehaviourWrap.Register(L);
		BoxColliderWrap.Register(L);
		CharacterControllerWrap.Register(L);
		ChatInterfaceWrap.Register(L);
		CLuaCallBackMgrWrap.Register(L);
		ColliderWrap.Register(L);
		ColorWrap.Register(L);
		ComponentBaseLuaWrap.Register(L);
		ComponentWrap.Register(L);
		ConstantsWrap.Register(L);
		DebuggerWrap.Register(L);
		DelegateWrap.Register(L);
		DwObjectWrap.Register(L);
		EEventTypeWrap.Register(L);
		EGameStateTypeWrap.Register(L);
		EnumTextWrap.Register(L);
		EnumWrap.Register(L);
		EventSysWrap.Register(L);
		EZFunButtonGroupWrap.Register(L);
		EZfunLimitScrollViewWrap.Register(L);
		EZFunScollViewWrap.Register(L);
		EZFunWindowEnumWrap.Register(L);
		GameObjectWrap.Register(L);
		GamePackageWrap.Register(L);
		IEnumeratorWrap.Register(L);
		LimitScrollViewDirectionWrap.Register(L);
		LuaModuleWrap.Register(L);
		LuaWindowRootWrap.Register(L);
		ModuleRootWrap.Register(L);
		ModuleTypeWrap.Register(L);
		MonoBehaviourWrap.Register(L);
		MouseOrTouchWrap.Register(L);
		NGUITextWrap.Register(L);
		NGUIToolsWrap.Register(L);
		ObjectWrap.Register(L);
		PlayerDataRefUtilWrap.Register(L);
		QuaternionWrap.Register(L);
		RessStorgeTypeWrap.Register(L);
		RessTypeWrap.Register(L);
		ScrollViewDirectionWrap.Register(L);
		TestConfigWrap.Register(L);
		TimeCountWrap.Register(L);
		TimerSysWrap.Register(L);
		TimeWrap.Register(L);
		TouchPhaseWrap.Register(L);
		TransformWrap.Register(L);
		TypeWrap.Register(L);
		UICameraWrap.Register(L);
		UIDraggableCameraWrap.Register(L);
		UIEventListenerWrap.Register(L);
		UILabelWrap.Register(L);
		UILuaExtendsWrap.Register(L);
		UIRectWrap.Register(L);
		UtilWrap.Register(L);
		Vector2Wrap.Register(L);
		Vector3Wrap.Register(L);
		Vector4Wrap.Register(L);
		VersionWrap.Register(L);
		WindowBaseLuaWrap.Register(L);
		WindowRootWrap.Register(L);
		WrapSysWrap.Register(L);
	}
}
