//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: tools/CAssetBundleData.proto
namespace tools.CAssetBundleData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CAssetBundleDataStruct")]
  public partial class CAssetBundleDataStruct : global::ProtoBuf.IExtensible
  {
    public CAssetBundleDataStruct() {}
    
    private string _m_ressGbName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_ressGbName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_ressGbName
    {
      get { return _m_ressGbName; }
      set { _m_ressGbName = value; }
    }
    private string _m_storeAssetBundleName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_storeAssetBundleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_storeAssetBundleName
    {
      get { return _m_storeAssetBundleName; }
      set { _m_storeAssetBundleName = value; }
    }
    private int _m_ressVersion;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"m_ressVersion", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_ressVersion
    {
      get { return _m_ressVersion; }
      set { _m_ressVersion = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CAssetBundleSceneDataStruct")]
  public partial class CAssetBundleSceneDataStruct : global::ProtoBuf.IExtensible
  {
    public CAssetBundleSceneDataStruct() {}
    
    private string _m_sceneName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_sceneName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_sceneName
    {
      get { return _m_sceneName; }
      set { _m_sceneName = value; }
    }
    private string _m_storeAssetBundleName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_storeAssetBundleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_storeAssetBundleName
    {
      get { return _m_storeAssetBundleName; }
      set { _m_storeAssetBundleName = value; }
    }
    private int _m_ressVersion;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"m_ressVersion", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_ressVersion
    {
      get { return _m_ressVersion; }
      set { _m_ressVersion = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CAssetBundleDependencies")]
  public partial class CAssetBundleDependencies : global::ProtoBuf.IExtensible
  {
    public CAssetBundleDependencies() {}
    
    private string _m_abName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_abName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_abName
    {
      get { return _m_abName; }
      set { _m_abName = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _m_dependenciesAb = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"m_dependenciesAb", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> m_dependenciesAb
    {
      get { return _m_dependenciesAb; }
    }
  
    private int _m_ressVersion;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"m_ressVersion", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_ressVersion
    {
      get { return _m_ressVersion; }
      set { _m_ressVersion = value; }
    }
    private bool _m_isStreamAsset = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"m_isStreamAsset", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool m_isStreamAsset
    {
      get { return _m_isStreamAsset; }
      set { _m_isStreamAsset = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResCABDataStructLs")]
  public partial class ResCABDataStructLs : global::ProtoBuf.IExtensible
  {
    public ResCABDataStructLs() {}
    
    private readonly global::System.Collections.Generic.List<CAssetBundleDataStruct> _list = new global::System.Collections.Generic.List<CAssetBundleDataStruct>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CAssetBundleDataStruct> list
    {
      get { return _list; }
    }
  
    private readonly global::System.Collections.Generic.List<CAssetBundleSceneDataStruct> _sceneList = new global::System.Collections.Generic.List<CAssetBundleSceneDataStruct>();
    [global::ProtoBuf.ProtoMember(2, Name=@"sceneList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CAssetBundleSceneDataStruct> sceneList
    {
      get { return _sceneList; }
    }
  
    private readonly global::System.Collections.Generic.List<CAssetBundleDependencies> _abDependencies = new global::System.Collections.Generic.List<CAssetBundleDependencies>();
    [global::ProtoBuf.ProtoMember(3, Name=@"abDependencies", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CAssetBundleDependencies> abDependencies
    {
      get { return _abDependencies; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}