//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: tools/ezfun_resource.proto
namespace ezfun_resource
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResText")]
  public partial class ResText : global::ProtoBuf.IExtensible
  {
    public ResText() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _text;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string text
    {
      get { return _text; }
      set { _text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResTextList")]
  public partial class ResTextList : global::ProtoBuf.IExtensible
  {
    public ResTextList() {}
    
    private readonly global::System.Collections.Generic.List<ezfun_resource.ResText> _list = new global::System.Collections.Generic.List<ezfun_resource.ResText>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ezfun_resource.ResText> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResPKCard")]
  public partial class ResPKCard : global::ProtoBuf.IExtensible
  {
    public ResPKCard() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _logicValue;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"logicValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int logicValue
    {
      get { return _logicValue; }
      set { _logicValue = value; }
    }
    private int _color;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"color", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int color
    {
      get { return _color; }
      set { _color = value; }
    }
    private string _ico_num;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"ico_num", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ico_num
    {
      get { return _ico_num; }
      set { _ico_num = value; }
    }
    private string _ico_big;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"ico_big", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ico_big
    {
      get { return _ico_big; }
      set { _ico_big = value; }
    }
    private string _sound;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"sound", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sound
    {
      get { return _sound; }
      set { _sound = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResPKCardList")]
  public partial class ResPKCardList : global::ProtoBuf.IExtensible
  {
    public ResPKCardList() {}
    
    private readonly global::System.Collections.Generic.List<ezfun_resource.ResPKCard> _list = new global::System.Collections.Generic.List<ezfun_resource.ResPKCard>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ezfun_resource.ResPKCard> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResMJCard")]
  public partial class ResMJCard : global::ProtoBuf.IExtensible
  {
    public ResMJCard() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _color;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"color", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int color
    {
      get { return _color; }
      set { _color = value; }
    }
    private string _ico;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ico", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ico
    {
      get { return _ico; }
      set { _ico = value; }
    }
    private string _sound;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"sound", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sound
    {
      get { return _sound; }
      set { _sound = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResMJCardList")]
  public partial class ResMJCardList : global::ProtoBuf.IExtensible
  {
    public ResMJCardList() {}
    
    private readonly global::System.Collections.Generic.List<ezfun_resource.ResMJCard> _list = new global::System.Collections.Generic.List<ezfun_resource.ResMJCard>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ezfun_resource.ResMJCard> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResSoundID")]
  public partial class ResSoundID : global::ProtoBuf.IExtensible
  {
    public ResSoundID() {}
    
    private int _Index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Index
    {
      get { return _Index; }
      set { _Index = value; }
    }
    private int _Type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private int _Sex;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Sex
    {
      get { return _Sex; }
      set { _Sex = value; }
    }
    private int _Language;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Language", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Language
    {
      get { return _Language; }
      set { _Language = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoundEvent")]
  public partial class SoundEvent : global::ProtoBuf.IExtensible
  {
    public SoundEvent() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _time;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResSound")]
  public partial class ResSound : global::ProtoBuf.IExtensible
  {
    public ResSound() {}
    
    private ezfun_resource.ResSoundID _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ezfun_resource.ResSoundID ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private readonly global::System.Collections.Generic.List<ezfun_resource.SoundEvent> _soundEvent = new global::System.Collections.Generic.List<ezfun_resource.SoundEvent>();
    [global::ProtoBuf.ProtoMember(2, Name=@"soundEvent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ezfun_resource.SoundEvent> soundEvent
    {
      get { return _soundEvent; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResSoundList")]
  public partial class ResSoundList : global::ProtoBuf.IExtensible
  {
    public ResSoundList() {}
    
    private readonly global::System.Collections.Generic.List<ezfun_resource.ResSound> _list = new global::System.Collections.Generic.List<ezfun_resource.ResSound>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ezfun_resource.ResSound> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResQuickVoiceID")]
  public partial class ResQuickVoiceID : global::ProtoBuf.IExtensible
  {
    public ResQuickVoiceID() {}
    
    private int _Index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Index
    {
      get { return _Index; }
      set { _Index = value; }
    }
    private int _Type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResQuickVoice")]
  public partial class ResQuickVoice : global::ProtoBuf.IExtensible
  {
    public ResQuickVoice() {}
    
    private ezfun_resource.ResQuickVoiceID _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ezfun_resource.ResQuickVoiceID ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _text;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string text
    {
      get { return _text; }
      set { _text = value; }
    }
    private string _voicePath;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"voicePath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string voicePath
    {
      get { return _voicePath; }
      set { _voicePath = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResQuickVoiceList")]
  public partial class ResQuickVoiceList : global::ProtoBuf.IExtensible
  {
    public ResQuickVoiceList() {}
    
    private readonly global::System.Collections.Generic.List<ezfun_resource.ResQuickVoice> _list = new global::System.Collections.Generic.List<ezfun_resource.ResQuickVoice>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ezfun_resource.ResQuickVoice> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}