//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: PrefabLabel.proto
namespace PrefabLabel
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PrefabLabeTotalMessage")]
  public partial class PrefabLabeTotalMessage : global::ProtoBuf.IExtensible
  {
    public PrefabLabeTotalMessage() {}
    
    private int _seqIndex;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seqIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seqIndex
    {
      get { return _seqIndex; }
      set { _seqIndex = value; }
    }
    private readonly global::System.Collections.Generic.List<PrefabeLabelMessage> _prefabLables = new global::System.Collections.Generic.List<PrefabeLabelMessage>();
    [global::ProtoBuf.ProtoMember(2, Name=@"prefabLables", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PrefabeLabelMessage> prefabLables
    {
      get { return _prefabLables; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PrefabeLabelMessage")]
  public partial class PrefabeLabelMessage : global::ProtoBuf.IExtensible
  {
    public PrefabeLabelMessage() {}
    
    private int _startSeq;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"startSeq", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int startSeq
    {
      get { return _startSeq; }
      set { _startSeq = value; }
    }
    private int _nowSeq;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nowSeq", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nowSeq
    {
      get { return _nowSeq; }
      set { _nowSeq = value; }
    }
    private readonly global::System.Collections.Generic.List<LabelNumMessage> _labelNums = new global::System.Collections.Generic.List<LabelNumMessage>();
    [global::ProtoBuf.ProtoMember(3, Name=@"labelNums", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<LabelNumMessage> labelNums
    {
      get { return _labelNums; }
    }
  
    private string _prefabeName;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"prefabeName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string prefabeName
    {
      get { return _prefabeName; }
      set { _prefabeName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LabeNumTotalMessage")]
  public partial class LabeNumTotalMessage : global::ProtoBuf.IExtensible
  {
    public LabeNumTotalMessage() {}
    
    private int _seqIndex;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seqIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seqIndex
    {
      get { return _seqIndex; }
      set { _seqIndex = value; }
    }
    private readonly global::System.Collections.Generic.List<LabelNumMessage> _labelNums = new global::System.Collections.Generic.List<LabelNumMessage>();
    [global::ProtoBuf.ProtoMember(2, Name=@"labelNums", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<LabelNumMessage> labelNums
    {
      get { return _labelNums; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LabelNumMessage")]
  public partial class LabelNumMessage : global::ProtoBuf.IExtensible
  {
    public LabelNumMessage() {}
    
    private string _transName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"transName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string transName
    {
      get { return _transName; }
      set { _transName = value; }
    }
    private int _labelNum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"labelNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int labelNum
    {
      get { return _labelNum; }
      set { _labelNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}